server {
  listen 80;
  server_name guest.${DOMAIN} barista.${DOMAIN} api.${DOMAIN};

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2;
  server_name guest.${DOMAIN};

  ssl_certificate /etc/letsencrypt/live/guest.${DOMAIN}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/guest.${DOMAIN}/privkey.pem;

  location / {
    proxy_pass http://guest:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

server {
  listen 443 ssl http2;
  server_name barista.${DOMAIN};

  ssl_certificate /etc/letsencrypt/live/barista.${DOMAIN}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/barista.${DOMAIN}/privkey.pem;

  location / {
    proxy_pass http://barista:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

server {
  listen 443 ssl http2;
  server_name api.${DOMAIN};

  ssl_certificate /etc/letsencrypt/live/api.${DOMAIN}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/api.${DOMAIN}/privkey.pem;

  client_max_body_size 2m;

  location / {
    proxy_pass http://backend:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
